In [23]:
import numpy as np
print("1) ", np.__version__)

1)  1.14.0


In [46]:
arr = np.arange(10)
print("2) ", arr)

2)  [0 1 2 3 4 5 6 7 8 9]


In [25]:
arr = np.full((3, 3), True, dtype=bool)
print("3) ", arr)

3)  [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [26]:
arr = np.arange(10)
oddArr = arr[arr % 2 == 1]
print("4) ", oddArr)

4)  [1 3 5 7 9]


In [27]:
arr = np.arange(10)
arr[arr % 2 == 1] = -1
print("5) ", arr)

5)  [ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [68]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print("6) ", arr, out)

6)  [0 1 2 3 4 5 6 7 8 9] [ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [41]:
arr = np.arange(10)
reshapeArr = arr.reshape(2, -1)
print("7) ", reshapeArr)

7)  [[0 1 2 3 4]
 [5 6 7 8 9]]


In [50]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
result = np.concatenate([a, b], axis=0)
print("8) ", result)

8)  [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [55]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
result = np.concatenate([a, b], axis=1)
print("9) ", result)

9)  [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [59]:
a = np.array([1,2,3])
result = np.r_[np.repeat(a, 3), np.tile(a, 3)]
print("10) ", result)

10)  [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [60]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
result = np.intersect1d(a,b)
print("11) ", result)

11)  [2 4]


In [61]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
result = np.setdiff1d(a,b)
print("12) ", result)

12)  [1 2 3 4]


In [62]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
result = np.where(a == b)
print("13) ", result)

13)  (array([1, 3, 5, 7]),)


In [63]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a >= 5) & (a <= 10))
print("14) ", a[index])

14)  [ 6  9 10]


In [65]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

result = pair_max(a, b)
print("15) ", result)

15)  [6. 7. 9. 8. 9. 7. 5.]


In [73]:
arr = np.arange(9).reshape(3,3)
result = arr[:, [1,0,2]]
print("16) ")
print(arr)
print("")
print(result)

16) 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [74]:
arr = np.arange(9).reshape(3,3)
result = arr[[1,0,2], :]
print("17) ")
print(arr)
print("")
print(result)

17) 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [76]:
arr = np.arange(9).reshape(3,3)
result = arr[::-1]
print("18) ")
print(arr)
print("")
print(result)

18) 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [77]:
arr = np.arange(9).reshape(3,3)
result = arr[:, ::-1]
print("19) ")
print(arr)
print("")
print(result)

19) 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [79]:
arr = np.arange(9).reshape(3,3)
random_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
print("20) ")
print(random_arr)

20) 
[[6.29393738 8.52909938 7.92679757]
 [5.49001213 9.8190814  5.2797446 ]
 [6.38012225 9.04167447 6.80891123]
 [8.10248668 7.09427086 5.8093519 ]
 [6.33992529 7.29368991 5.55791568]]


In [82]:
arr = np.arange(9).reshape(3,3)
random_arr = np.random.random((5,3)) 
np.set_printoptions(precision=3)
print("21) ")
print(random_arr)

21) 
[[0.429 0.808 0.671]
 [0.718 0.067 0.71 ]
 [0.05  0.9   0.734]
 [0.925 0.825 0.23 ]
 [0.406 0.612 0.375]]


In [84]:
np.set_printoptions(suppress=False)
np.random.seed(100)
random_arr = np.random.random([3,3])/1e3
print("22) ")
print(random_arr)
np.set_printoptions(suppress=True, precision=6)
print(random_arr)

22) 
[[5.434049e-04 2.783694e-04 4.245176e-04]
 [8.447761e-04 4.718856e-06 1.215691e-04]
 [6.707491e-04 8.258528e-04 1.367066e-04]]
[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


In [85]:
np.set_printoptions(threshold=6)
a = np.arange(15)
print("23) ")
print(a)

23) 
[ 0  1  2 ... 12 13 14]


In [123]:
np.set_printoptions(threshold=6)
a = np.arange(15)
print("24) ")
print(a)
np.set_printoptions(threshold=np.nan)
print(a)

24) 
[ 0  1  2 ... 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [89]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
print("25) ")
print(iris[:3])

25) 
[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']]


In [135]:
from json import load
from sys import argv

nb = '25-numpy-python-exercises.ipynb'

cells = load(open(nb))['cells']
loc = sum(len(c['source']) for c in cells if c['cell_type'] == 'code')

arr = np.arange(26)
new_arr = np.delete(arr, [0])

for x in new_arr:
    print("I read the " + str(x) + ". exersise!")
    
print("")
print("And wrote " + str(loc) + " Lines of Code!")

I read the 1. exersise!
I read the 2. exersise!
I read the 3. exersise!
I read the 4. exersise!
I read the 5. exersise!
I read the 6. exersise!
I read the 7. exersise!
I read the 8. exersise!
I read the 9. exersise!
I read the 10. exersise!
I read the 11. exersise!
I read the 12. exersise!
I read the 13. exersise!
I read the 14. exersise!
I read the 15. exersise!
I read the 16. exersise!
I read the 17. exersise!
I read the 18. exersise!
I read the 19. exersise!
I read the 20. exersise!
I read the 21. exersise!
I read the 22. exersise!
I read the 23. exersise!
I read the 24. exersise!
I read the 25. exersise!

And wrote 126 Lines of Code!
